# Generated by Django 6.0.1 on 2026-01-15 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('beds', models.PositiveIntegerField()),
                ('rooms', models.PositiveIntegerField()),
                ('is_user_approved', models.BooleanField(db_index=True, default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.category')),
                ('federation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.facility')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilityDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveIntegerField()),
                ('overnight_stays', models.PositiveIntegerField()),
                ('total_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_costs', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_published', models.BooleanField(db_index=True, default=False)),
                ('last_published_at', models.DateTimeField(blank=True, null=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_details', to='facilities.facility')),
            ],
            options={
                'db_table': 'facilitie_details',
            },
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['user', 'is_user_approved'], name='facilities_user_id_f45d43_idx'),
        ),
        migrations.AddIndex(
            model_name='facilitydetail',
            index=models.Index(fields=['is_published', 'facility'], name='facilitie_d_is_publ_df802e_idx'),
        ),
        migrations.AddConstraint(
            model_name='facilitydetail',
            constraint=models.UniqueConstraint(condition=models.Q(('is_published', True)), fields=('facility', 'year'), name='unique_published_per_year_per_facility'),
        ),
    ]
