# Generated by Django 6.0.1 on 2026-01-24 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='is_federation',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='FacilityActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.TextField()),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='facilities.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facility_activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facility_activity_logs',
            },
        ),
    ]
