# Generated by Django 6.0.1 on 2026-02-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0002_facility_is_federation_facilityactivitylog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facilitydetail',
            options={'ordering': ['-year']},
        ),
    ]
