# Generated by Django 6.0.1 on 2026-02-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0003_alter_facilitydetail_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='beds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='rooms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
