# Generated by Django 6.0.1 on 2026-02-21 11:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0004_alter_facility_beds_alter_facility_rooms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='federal_state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facility',
            name='opening_days_per_year',
            field=models.PositiveIntegerField(default=365),
        ),
        migrations.AddField(
            model_name='facility',
            name='operational_building_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facility',
            name='total_property_area',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='catering_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cost of Goods / Catering Costs'),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='cleaning_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='energy_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='guests',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='income_from_accomodation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Revenue Share Accommodation'),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='income_from_catering',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Revenue Share Catering'),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='income_from_conferences',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Revenue Share Conferences'),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='income_from_donations',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Revenue Share Donations, Grants / Subsidies'),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='maintenance_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Maintenance and Other Operating Costs'),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='personnel_costs',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='facilitydetail',
            name='rooms_sold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='facilitydetail',
            name='total_costs',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['category', 'user', 'is_user_approved'], name='facilities_categor_752282_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['is_federation', 'federation', 'user', 'is_user_approved'], name='facilities_is_fede_eac85f_idx'),
        ),
        migrations.AddIndex(
            model_name='facility',
            index=models.Index(fields=['federation', 'user', 'is_user_approved'], name='facilities_federat_0f79b3_idx'),
        ),
    ]
