# Generated by Django 6.0.1 on 2026-03-13 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0005_facility_federal_state_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facilities', to='facilities.category'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to='facilities.facility'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facilities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='facilityactivitylog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
