# Generated by Django 6.0.1 on 2026-03-16 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facilities', '0007_auto_20260314_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitydetail',
            name='cleaning_costs',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='facilitydetail',
            name='rooms_sold',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
