# Generated by Django 6.0.1 on 2026-02-27 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_password_changed_at_useractivitylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('federation_manager', 'Federation Manager'), ('facility_manager', 'Facility Manager')], max_length=20)),
                ('token', models.CharField(editable=False, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(editable=False)),
            ],
            options={
                'db_table': 'user_invitations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'token'], name='user_invita_email_2b0db7_idx')],
            },
        ),
    ]
