# Generated by Django 6.0.1 on 2026-03-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('federation_manager', 'Verbandsmanager'), ('facility_manager', 'Facility Manager')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('federation_manager', 'Verbandsmanager'), ('facility_manager', 'Facility Manager')], max_length=20),
        ),
    ]
